### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException
  id: LinqDataSourceValidationException
  children:
  - System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor
  - System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)
  - System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})
  - System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)
  - System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions
  langs:
  - csharp
  name: LinqDataSourceValidationException
  nameWithType: LinqDataSourceValidationException
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException
  type: Class
  summary: "Beschrijft een uitzondering is opgetreden tijdens de validatie van nieuw of gewijzigd van waarden voordat waarden worden ingevoegd, bijgewerkt of verwijderd door een <xref href=&quot;System.Web.UI.WebControls.LinqDataSource&quot;> </xref> besturingselement."
  remarks: "De klasse LinqDataSourceValidationException bevat typeconversie en uitzonderingen voor eigenschap-setter. Alle uitzonderingen die zijn gegenereerd tijdens de validatie zijn opgenomen in de <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A>verzameling.</xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> U kunt elke uitzondering validatie ophalen doorloopt de <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A>verzameling.</xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A>       Doorgaans verwerken van uitzonderingen in de <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, en <xref:System.Web.UI.WebControls.LinqDataSource.Inserting>gebeurtenissen.</xref:System.Web.UI.WebControls.LinqDataSource.Inserting> </xref:System.Web.UI.WebControls.LinqDataSource.Deleting> </xref:System.Web.UI.WebControls.LinqDataSource.Updating> Als een validatie-uitzondering is opgetreden, de `Exception` eigenschap van de <xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs>, <xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs>, of <xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs>object bevat een object LinqDataSourceValidationException.</xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs> </xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs> </xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs> Als er geen uitzondering, de `Exception` eigenschap bevat `null`.       Voor het afhandelen van validatie uitzonderingen maken een handler voor de <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, of <xref:System.Web.UI.WebControls.LinqDataSource.Inserting>gebeurtenis.</xref:System.Web.UI.WebControls.LinqDataSource.Inserting> </xref:System.Web.UI.WebControls.LinqDataSource.Deleting> </xref:System.Web.UI.WebControls.LinqDataSource.Updating> Schakel in de gebeurtenis-handler of de `Exception` eigenschap van de klasse event argument bevat een waarde dan `null`. Als de `Exception` eigenschap niet null is, een of meer validatie-uitzonderingen veroorzaakt en kunt u elke uitzondering validatie in ophalen de <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A>eigenschap.</xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A>       Een validatie-uitzondering kan optreden als een waarde komt niet overeen met het type van de eigenschap. Bijvoorbeeld, het bijwerken van een integer-eigenschap met behulp van niet-numerieke tekens zorgt ervoor dat een validatie-uitzondering. Een LINQ to SQL-klasse kan ook aangepaste validatiecriteria die zorg ervoor dat de eigenschap een waarde die binnen een verwachte bereik of een patroon bevat bevatten."
  example:
  - "The following example shows an event handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating> event. It displays any validation exception messages by using a <xref:System.Web.UI.WebControls.Label> control.  \n  \n```vb#  \nProtected Sub LinqDataSource_Updating(ByVal sender As Object, _  \n        ByVal e As LinqDataSourceUpdateEventArgs)  \n    If (e.Exception IsNot Nothing) Then  \n        For Each innerException As KeyValuePair(Of String, Exception) _  \n               In e.Exception.InnerExceptions  \n            Label1.Text &= innerException.Key & \": \" & _  \n                innerException.Value.Message & \"<br />\"  \n        Next  \n        e.ExceptionHandled = True  \n    End If  \nEnd Sub  \n```  \n  \n [C#]  \n  \n```  \nprotected void LinqDataSource_Updating(object sender,   \n        LinqDataSourceUpdateEventArgs e)  \n{  \n    if (e.Exception != null)  \n    {  \n        foreach (KeyValuePair<string, Exception> innerException in   \n             e.Exception.InnerExceptions)  \n        {  \n        Label1.Text += innerException.Key + \": \" +   \n            innerException.Value.Message + \"<br />\";  \n        }  \n        e.ExceptionHandled = true;  \n    }  \n}  \n```"
  syntax:
    content: 'public class LinqDataSourceValidationException : Exception, System.Web.DynamicData.IDynamicValidatorException'
  inheritance:
  - System.Exception
  implements:
  - System.Web.DynamicData.IDynamicValidatorException
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor
  id: '#ctor'
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  langs:
  - csharp
  name: LinqDataSourceValidationException()
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException()
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.UI.WebControls
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.UI.WebControls.LinqDataSourceValidationException&quot;> </xref> klasse met een systeem geleverd bericht met een beschrijving van de fout."
  remarks: "Het systeem geleverd bericht met een beschrijving van de fout wordt rekening gehouden met de huidige systeemcultuur.       De volgende tabel toont de eerste waarden voor een exemplaar van de <xref:System.Web.UI.WebControls.LinqDataSourceValidationException>klasse.</xref:System.Web.UI.WebControls.LinqDataSourceValidationException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Gelokaliseerde beschrijving van een systeem geleverd. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public LinqDataSourceValidationException ();
    parameters: []
  overload: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  langs:
  - csharp
  name: LinqDataSourceValidationException(String)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(String)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(String)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.UI.WebControls
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.UI.WebControls.LinqDataSourceValidationException&quot;> </xref> klasse met een opgegeven bericht met een beschrijving van de fout."
  remarks: "De volgende tabel toont de eerste waarden voor een exemplaar van de <xref:System.Web.UI.WebControls.LinqDataSourceValidationException>klasse.</xref:System.Web.UI.WebControls.LinqDataSourceValidationException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public LinqDataSourceValidationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de fout wordt beschreven."
  overload: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  langs:
  - csharp
  name: LinqDataSourceValidationException(SerializationInfo,StreamingContext)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(SerializationInfo,StreamingContext)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.UI.WebControls
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.UI.WebControls.LinqDataSourceValidationException&quot;> </xref> klasse met de geserialiseerde gegevens."
  remarks: "Deze constructor is aangeroepen tijdens de deserialisatie voor het opnieuw samenstellen van de uitzondering-object dat wordt verzonden via een stroom."
  syntax:
    content: protected LinqDataSourceValidationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat de gegevens geserialiseerd object bevat."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Contextinformatie over de bron- of doelserver."
  overload: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})
  id: '#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})'
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  langs:
  - csharp
  name: LinqDataSourceValidationException(String,IDictionary<String,Exception>)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(String,IDictionary<String,Exception>)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(String,IDictionary<String,Exception>)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.UI.WebControls
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.UI.WebControls.LinqDataSourceValidationException&quot;> </xref> klasse met een opgegeven bericht met een beschrijving van de fout en een verzameling met verwijzingen naar interne uitzonderingen."
  syntax:
    content: public LinqDataSourceValidationException (string message, System.Collections.Generic.IDictionary<string,Exception> innerExceptions);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de fout wordt beschreven."
    - id: innerExceptions
      type: System.Collections.Generic.IDictionary{System.String,System.Exception}
      description: "De verzameling van uitzonderingen voor validatie."
  overload: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  langs:
  - csharp
  name: LinqDataSourceValidationException(String,Exception)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(String,Exception)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(String,Exception)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.UI.WebControls
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Web.UI.WebControls.LinqDataSourceValidationException&quot;> </xref> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering."
  remarks: "U doorgaans maakt geen gebruik deze constructor omdat validatie uitzonderingen worden opgeslagen in de <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A>-eigenschap niet de <xref:System.Exception.InnerException%2A>eigenschap.</xref:System.Exception.InnerException%2A> </xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A>"
  syntax:
    content: public LinqDataSourceValidationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de fout wordt beschreven."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering."
  overload: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: LinqDataSourceValidationException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.UI.WebControls
  summary: "Hiermee haalt u informatie over de uitzondering en deze toevoegt aan de <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> object."
  remarks: "De methode GetObjectData, komen voegt u informatie over de uitzondering op de <xref:System.Runtime.Serialization.SerializationInfo>-object dat is bedoeld voor serialisatie.</xref:System.Runtime.Serialization.SerializationInfo> Tijdens de deserialisatie-de uitzondering is aangemaakt de <xref:System.Runtime.Serialization.SerializationInfo>die via de stroom is verzonden.</xref:System.Runtime.Serialization.SerializationInfo>"
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Het object dat bevat de gegevens geserialiseerd object voor de uitzondering die wordt gegenereerd."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Contextinformatie over de bron- of doelserver."
  overload: System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions
  id: InnerExceptions
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  langs:
  - csharp
  name: InnerExceptions
  nameWithType: LinqDataSourceValidationException.InnerExceptions
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.UI.WebControls
  summary: "Hiermee haalt u een of meer uitzonderingen die is opgetreden bij het verifiëren van nieuwe of gewijzigde gegevens."
  remarks: "De verzameling bevat alle validatie-uitzonderingen die zijn gegenereerd tijdens de gegevensvalidatie voordat u een update InnerExceptions invoegen of verwijderen. Een validatie-uitzondering kan optreden als een waarde komt niet overeen met het type van de eigenschap. Als u probeert een integer-eigenschap bijwerken met behulp van niet-numerieke tekens, wordt bijvoorbeeld een validatie-uitzondering opgetreden. Een LINQ to SQL-klasse kan ook aangepaste validatiecriteria die zorg ervoor dat de eigenschap een waarde die binnen een verwachte bereik of een patroon bevat bevatten."
  example:
  - "The following example shows an event handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating> event. It displays any validation exception messages by using a <xref:System.Web.UI.WebControls.Label> control.  \n  \n```vb#  \nProtected Sub LinqDataSource_Updating(ByVal sender As Object, _  \n        ByVal e As LinqDataSourceUpdateEventArgs)  \n    If (e.Exception IsNot Nothing) Then  \n        For Each innerException As KeyValuePair(Of String, Exception) _  \n                In e.Exception.InnerExceptions  \n          Label1.Text &= innerException.Key & \": \" & _   \n                  innerException.Value.Message & \"<br />\"  \n        Next  \n        e.ExceptionHandled = True  \n    End If  \nEnd Sub  \n```  \n  \n [C#]  \n  \n```  \nprotected void LinqDataSource_Updating(object sender,   \n        LinqDataSourceUpdateEventArgs e)   \n{  \n    if (e.Exception != null)  \n    {  \n        foreach (KeyValuePair<string, Exception> innerException in   \n            e.Exception.InnerExceptions)  \n        {  \n            Label1.Text += innerException.Key + \": \" +   \n                innerException.Message + \"<br />\";  \n        }  \n        e.ExceptionHandled = true;  \n    }  \n}  \n```"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,Exception> InnerExceptions { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Exception}
      description: "Een verzameling waartoe de uitzonderingen."
  overload: System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: LinqDataSourceValidationException()
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException()
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException()
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: LinqDataSourceValidationException(String)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(String)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: LinqDataSourceValidationException(SerializationInfo,StreamingContext)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(SerializationInfo,StreamingContext)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: LinqDataSourceValidationException(String,IDictionary<String,Exception>)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(String,IDictionary<String,Exception>)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(String,IDictionary<String,Exception>)
- uid: System.Collections.Generic.IDictionary{System.String,System.Exception}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,Exception>
  nameWithType: IDictionary<String,Exception>
  fullName: System.Collections.Generic.IDictionary<System.String,System.Exception>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.String,System.Exception>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Exception
    name: Exception
    nameWithType: Exception
    fullName: Exception
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: LinqDataSourceValidationException(String,Exception)
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException(String,Exception)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.LinqDataSourceValidationException(String,Exception)
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: LinqDataSourceValidationException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: InnerExceptions
  nameWithType: LinqDataSourceValidationException.InnerExceptions
  fullName: System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor*
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: LinqDataSourceValidationException
  nameWithType: LinqDataSourceValidationException.LinqDataSourceValidationException
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData*
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: GetObjectData
  nameWithType: LinqDataSourceValidationException.GetObjectData
- uid: System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions*
  parent: System.Web.UI.WebControls.LinqDataSourceValidationException
  isExternal: false
  name: InnerExceptions
  nameWithType: LinqDataSourceValidationException.InnerExceptions
